Спринт №15.1
PisarevAlexander/java-shareit pull request #3
Opened 2023-08-01 16:43 UTC by PisarevAlexander

2023-08-03 19:55 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-08-03 19:55 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +    List<ItemRequestDto> getAllWithSize(int from, int size, long userId);
Необязательно придумывать другое название методу getAllWithSize.
Пусть будет тоже, но с другими параметрами - другая сигнатура, вопрос на засыпку: как это называется?

`List<ItemRequestDto> getAllWithSize(long userId, int from, int size);`

И второе, а почему бы не передавать уже сюда не два параметра, а один - сам `Pageable` ?

2023-08-03 19:55 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        if (!itemRequests.isEmpty()) {
Вот тут лучше инвертировать условие.
Это уберет лишнюю вложенность.
И в целом хороший паттерн - начать метод с условия выхода из него.

```
        if (itemRequests.isEmpty()) {
            return new ArrayList<>();
        }
        
        ....
```

2023-08-04 12:20 UTC, PisarevAlexander commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +    List<ItemRequestDto> getAllWithSize(int from, int size, long userId);
Добавил перегрузку метода.

2023-08-04 19:24 UTC, FanaticFiz approved these changes

2023-08-05 03:58 UTC, merged