Add docker
PisarevAlexander/java-shareit pull request #4
Opened 2023-08-08 13:39 UTC by PisarevAlexander

2023-08-08 19:43 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-08-08 19:43 UTC, FanaticFiz commented on gateway/pom.xml
> +        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
Эти параметры могут быть прописаны единажды в родительском `pom`

2023-08-08 19:43 UTC, FanaticFiz commented on server/pom.xml
> +			<artifactId>spring-boot-starter-validation</artifactId>
Валидация только на `gateway`

2023-08-08 19:43 UTC, FanaticFiz commented on server/src/test/java/ru/practicum/shareit/request/ItemRequestControllerIntegrationTest.java
> +import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
Тут у нас
- лишняя переменная `private ItemRequest itemRequest;`
- переменная `LocalDateTime time;` тоже как бы лишняя - дальше метода `setUp` её нет.
Ну и в других классах эта переменная неоправданно вынесена из этого метода.

2023-08-08 19:43 UTC, FanaticFiz commented on server/src/main/resources/application.yml
> +    password: ${POSTGRES_PASSWORD}
Свойства переехали 

```
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto:
    show-sql: true
```

2023-08-08 19:43 UTC, FanaticFiz commented on server/src/main/java/ru/practicum/shareit/booking/BookingRepository.java
`findBookingByBooker_IdAndItem_IdAndAndEndBefore`

Тут опечатка в метода два `And` подряд...
Но это ни на что не влияет, поскольку метод не используется.

2023-08-09 14:24 UTC, PisarevAlexander commented on server/pom.xml
> +			<artifactId>spring-boot-starter-validation</artifactId>
Не знаю почему, но если убрать зависимость, то тесны репозитория начинают падать.

2023-08-09 14:27 UTC, PisarevAlexander commented on server/src/main/java/ru/practicum/shareit/booking/BookingRepository.java
Метод используется в сервисе, опечатку поправил.

2023-08-09 18:38 UTC, FanaticFiz approved these changes

2023-08-10 05:59 UTC, merged